### ISSUE TITLE
include/raikv/util.h : missing #include <stdlib.h>

### ISSUE THREAD

**Issue by julio77it** [raitechnology/raikv#1]
Hi, 

I'm compiling **raitechnology/build** on **RH7** and I'm getting these errors : 

In file included from include/raids/redis_hyperloglog.h:4:0,
                 from test/test_hllnum.cpp:9:
raikv/include/raikv/util.h: In function ‘void* rai::kv::aligned_malloc(size_t)’:
raikv/include/raikv/util.h:131:10: error: ‘::aligned_alloc’ has not been declared
   return ::aligned_alloc( KV_CACHE_ALIGN, sz ); /* >= RH7 */
          ^
raikv/include/raikv/util.h: In function ‘void rai::kv::aligned_free(void*)’:
raikv/include/raikv/util.h:140:3: error: ‘::free’ has not been declared
   ::free( p ); /* libc allows this */
   
I've added this include in include/raikv/util.h at line 4 :

#include <stdlib.h>

and now it works.

**Comment by injinj** [comment]
ok, thanks
